---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## (d)

```{r}
# menchild30bach.dat
Y_a = c(1, 0, 0, 1, 2, 2, 1, 5, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 2,
        1, 3, 2, 0, 0, 3, 0, 0, 0, 2, 1, 0, 2, 1, 0, 0, 1, 3, 0, 1, 1, 0, 2, 0,
        0, 2, 2, 1, 3, 0, 0, 0, 1, 1)
# menchild30nobach.dat
Y_b = c(2, 2, 1, 1, 2, 2, 1, 2, 1, 0, 2, 1, 1, 2, 0, 2, 2, 0, 2, 1, 0, 0, 3, 6,
        1, 6, 4, 0, 3, 2, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 4, 2, 1, 0, 0,
        1, 0, 3, 2, 5, 0, 1, 1, 2, 1, 2, 1, 2, 0, 0, 0, 2, 1, 0, 2, 0, 2, 4, 1,
        1, 1, 2, 0, 1, 1, 1, 1, 0, 2, 3, 2, 0, 2, 1, 3, 1, 3, 2, 2, 3, 2, 0, 0,
        0, 1, 0, 0, 0, 1, 2, 0, 3, 3, 0, 1, 2, 2, 2, 0, 6, 0, 0, 0, 2, 0, 1, 1,
        1, 3, 3, 2, 1, 1, 0, 1, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0, 0, 2, 2, 4, 1, 2,
        3, 2, 0, 0, 0 ,1, 0, 0, 1, 5, 2, 1, 3, 2, 0, 2, 1, 1, 3, 0, 5, 0, 0, 2,
        4, 3, 4, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 3, 3, 2, 
        2, 0, 0, 2, 3, 2, 4, 3, 3, 4, 0, 3, 0, 1, 0, 1, 2, 3, 4, 1, 2, 6, 2, 1,
        2, 2)
# set some values
n_a = length(Y_a)
n_b = length(Y_b)
ybar_a = mean(Y_a)
ybar_b = mean(Y_b)
a_theta = 2
b_theta = 1
S = 10000
ab_gamma = c(8, 16, 32, 64, 128)

theta_diff = sapply(ab_gamma, function(abg) {
  a_gamma = b_gamma = abg
  THETA = numeric(S)
  GAMMA = numeric(S)
  theta = ybar_a
  gamma = ybar_a / ybar_b 
  for (s in 1:S) {
    theta = rgamma(1, a_theta + n_a * ybar_a + n_b * ybar_b, b_theta + n_a + n_b * gamma)
    gamma = rgamma(1, a_gamma + n_b * ybar_b, b_gamma + n_b * theta)

    THETA[s] = theta
    GAMMA[s] = gamma
  }
  THETA_A = THETA
  THETA_B = THETA * GAMMA

  mean(THETA_B - THETA_A)
})

theta_diff
```

We obtained the expected value of the difference of theta with each value of gamma a and gamma b as follow. We can see that as we increase the value of gamma a and gamma b(increase the prior belief), the mean posterior difference between thetas decreases.
