---
title: "assignment3"
output:
  pdf_document:
    latex_engine: xelatex

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Problem 1. (2)
```{r}
alpha1 = rbeta(10000, 295, 308)
alpha2 = rbeta(10000, 289, 333)
difference <- alpha2 - alpha1
hist(difference,nclass=50)
sum(difference > 0) / length(difference)
```
The plot are shown above, and we calculate the posterior probability that there was a shift toward Bush which is around 19%.

### Problem 2
$M1:\mu>1$

$M2: \mu\le1$

```{r}
hours <- c(1.2, 2.4, 1.3, 1.3, 0.0, 1.2, 1.6, 0.8, 0.6, 1.4)
xm <-mean(hours)
s <-sd(hours)
mu0 <-c(0,1)
n=length(hours)
tau<-1
a = (1-dnorm(xm,0,1))/dnorm(xm,0,1)
b = (1-dnorm(xm,(0+sum(xm))/(n+1),1/(n+1)))/dnorm(xm,(0+sum(xm))/(n+1),1/(n+1))
```
We can see from the result that for μ ∼N(0,1), the bayes factor is large, so there is very strong favor for M1 that μ>1. While for μ ∼N(1,1), the bayes factor is very weak, lead us the reject the null hypothesis. 


